language: node_js

sudo: false

node_js:
  - 'stable'
  - '6'

install:
  - npm install

cache:
  directories:
    - node_modules
    
deploy:
  provider: heroku
  api_key: HEROKU_API_KEY
  strategy: git