language: node_js

sudo: false

node_js:
  - 'stable'

install:
  - npm install
  - tsc
  - rm -rf node_modules

cache:
  directories:
    - node_modules

before-deploy:
  - git filter-branch -- --all # for azure only

deploy:
  - provider: azure_web_apps
    site: jokio-graph
    verbose: true
    skip_cleanup: true
  - provider: heroku
    app: jokio-graph
    api_key: $HEROKU_API_KEY
    skip_cleanup: true

notifications:
  slack:
    rooms:
      - $SLACK_KEY
    on_success: always # default: always
    on_failure: always # default: always