language: node_js

sudo: false

node_js:
  - 'stable'

install:
  - npm install

cache:
  directories:
    - node_modules

before_deploy:
  - tsc
  - rm -rf node_modules

# deploy:
#   provider: azure_web_apps
#   verbose: true
#   skip_cleanup: true

deploy:
  provider: heroku
  api_key: HEROKU_API_KEY
  app: jok-graph