language: node_js

sudo: false

node_js:
  - 'stable'

git:
   depth: 9999999

install:
  - npm install
  - tsc
  - rm -rf node_modules

cache:
  directories:
    - node_modules

deploy:
  - provider: azure_web_apps
    site: jokio-graph
    verbose: true
    skip_cleanup: true
  - provider: heroku
    app: jokio-graph
    api_key: $HEROKU_API_KEY
    skip_cleanup: true

notifications:
  - slack: 1lktaqFnKvkU6z+sZSodF2RZRVWWP1CFf8V8pUQ7Sio9FViNyqteu6mBbBskb13JF/7npoQVSqhLkKNY/nnWqDjrj0U5HfbQYUNsOJb4YGUlTmvasls5Z0TEEQku5aZ/agj4ahDn++AuqnRHjhOGZDJjR7bfG94In6Q4ZZg8AiG34LuBtezsIizZ7sNM1V+qxtPmxD1m/yGp8U9dCCcWFrS38Jhai70avPjqENNwZHgEHyJ3B7Jt35S1GASKh2yCphGpGmEat9ebXMjn4CJp5+ikrhaLlVw65djz4kFizmNoWEi8yGLYPl5f3SkecUk4UxBejpv4Ts0U3GpIgwASJoTQ6QqPy3RpInY7OHsMiy6GUeR8u8/lTODLnDGWQj+zXFZf6/7sJ+fOwxk2xz7EBe1idD4Z2Jckl401WK4VfSl56yatkd4XhRCbJFY30sx6xO5nej6weQ9AS6ZWcsewYVXJvW+82w5Vp21LIlE+6T61eRcbi50BLhzJN3rhjTgqXENt1+2rD2Zz6OaSGt+HQuI2W7Mrmh9NrSGOn4ETSEV7kjjLD3c2DQPbIsxjCH4oPC6TpxxPy5Dk4So7YtdQoXbdvT+yy2um8cQJZ7/MrFoNN1/WHtIGP4n0hx9ghgv00rsiPHKLMvg1vtEJwYCdppk90hAGsIZgTx21RvwrxVQ=
  - email:
      recipients:
      - ez@jok.io
      on_success: never
      on_failure: always
