language: node_js

sudo: false

node_js:
  - 'stable'

install:
  - yarn
  - tsc
  - rm -rf node_modules

cache: yarn

deploy:
  - provider: heroku
    app: jokio-graph
    api_key: $HEROKU_API_KEY
    skip_cleanup: true
  - provider: npm
    email: ez@jok.io
    skip_cleanup: true
    api_key:
      secure: Sd+0eKT/YRkJxUwU9jBBuwH8O579RF32lX7H0+AD5o9CEWV8wv2QNOpF8/HXiQ9kVfrb/uwRcNQAoRJq+wLr7QuazZgslvvt07MwKkQF2svyJYaqtISEdjkADyyhhO8y7Yt4PNETSb28FK3bM5qNv7vOjpYDEESdHmnGEy24MLMjucGEGs1Qtp+GOeCLDPg+jzSGkyYCWztvdg4GT2eKerUlgR20xAK8/oa4sZelCbE3AeLm2NZnSSgtjQe1vs2Z2R7AmLmFe3stmBGYqXm4b8TlESMXx9oV7PaGrPHxBalhuprjBVgp3Ym0FrZg3BjW+mzJy+I/Ho2hsAC4m+AMt3J4+qadsQrCbLqNOkAd61s5WbGjH2G+fFK9QqOgevZV6/mUFzWSudBvH+jN3BvL2eVnK474EgI/9hTNosu8z0YmJznr3+ptb37+l86nxmV8c9klL6o1r64WRbY/PNtZKQwlUgHc+MIoLYpF0YXoPAW/4hnA6MXmha74WY6C7LKbag44P0CxhX37TeOA+OKAfSBG0vWuW+gkVyVmgJoev8jqONjisJTNzjXIHVLjPoJAFoMliwCgkMoACuJOiuiozCnskDXOfrUfxP/NDw6w9wRW814cRmYenPEjTYCrTfMR+tz2MvCeo+vzKEy1WajCevRsNf3ouVwuW2QAh0KRDIg=

notifications:
  slack:
    rooms:
      secure: Jr9YnrBNQ0XQJbGwbxUU+2SaDeZLDwuULWL/9kDHfTd1X0F4DudWMFKlEbrilU/9iNx6t8od53LNI8CYyOALJSCGUi6Uzfb+u+DOJogKOeWTe5pZ+tRs8DPXlHme5xOpV1qlQSoKe5uF0wnKz7WQtOuj9ziZ2Isj5aasV6/KxfRk4kx3J/gS8RqcnMZ2eoD4q3mUr1qMxCLNQkQFNuly1MZNTsFtoYccJKNmH6VvqKUXwz/gdHTWysWGMaVdN98baAXNhMzkOaUFbiARE2I12fr1d7ewQnPRh4IHd/3s4F87GR/TVAA9OxEB4UAclVuMI/WXe/uGNyQ+O7jHdS288+0khDwj3BjCTMfPjhYoxIYW9F7C02BZBTYnLc1l+YPQxEY1CPVJg0n33x+TtHAWpeDxn+aqz+jIc0Cku7gev9Ta8t6/rx2cHjFtlPGm6pP5Bc6v3zRkydS/WHZ1rQCwvaly5VADsU7nXnEbExRvfyBhdyClPAlgviODRXGE9uMkbMgoKZON6q01PJrP8UMPmetNzeGADf3Z7DfIQfqEIlRcByjHh1aS2QIAxrVfsDg0/XDEuEO5kQ/zpwKdUPZknL358Badcd7bOcugRraz6NOLq4hci+Y63EFgjH9Mo5+fyBFiNdXwGy9iQ5hZlTMo8x5g7ts0tZaCtFxV3wkNAlo=
