
enum Gender {
  male
  female
}

enum Language {
  en
  ge
  ru
}

type Profile {
  facebook: FacebookProfile
  joker: JokerProfile
}

type User {
  id: Int!
  nick: String!
  gender: Gender!
  avatarUrl: String!
  isVIP: Boolean!
  language: Language!

  musicChannels(includeOfflines: Boolean): [Channel]!

  profile: Profile
}


type Query {
  user(id: Int): User
}
