
enum Gender {
  male
  female
}

enum Language {
  en
  ge
  ru
}

type User {
  id: Int!
  nick: String!
  gender: Gender!
  avatarUrl: String!
  avatar: String
  isVIP: Boolean!
  language: Language!

  musicChannels(includeOfflines: Boolean): [Channel]!
}


type Query {
  # Default current user
  user(id: Int): User
}
